Lecture 2 skeleton
js-tasks-ru/htmlcss-20230227_nadya-karandasheva pull request #10
Opened 2023-03-12 13:28 UTC by Nadya-Karandasheva

2023-03-12 13:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 00:19 UTC, GSemikozov requested changes

2023-03-15 00:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__container {
.skeleton

2023-03-15 00:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
лишнее ограничение ширины

2023-03-15 00:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.short {
.skeleton__content_short

2023-03-15 00:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину в процентах (приблизительно)

2023-03-15 00:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.medium {
и тут

2023-03-18 21:30 UTC, GSemikozov approved these changes

2023-03-18 21:30 UTC, merged