Cards main page
js-tasks-ru/htmlcss-20230227_nadya-karandasheva pull request #11
Opened 2023-03-12 14:04 UTC by Nadya-Karandasheva

2023-03-12 14:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-15 00:20 UTC, GSemikozov requested changes

2023-03-15 00:20 UTC, GSemikozov commented on components/cards/cards.css
> +.cards__container {
.cards

2023-03-15 00:20 UTC, GSemikozov commented on components/cards/cards.css
> +    padding: 68px 165px 204px 165px;
вместо таких паддингов по краям нужно использовать container

2023-03-15 00:20 UTC, GSemikozov commented on index.html
> +                        <p class="cart__title">Tooltip</p>
если тайтл то например h4

2023-03-18 07:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-18 08:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-18 08:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-18 08:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-18 08:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-18 21:33 UTC, GSemikozov requested changes

2023-03-18 21:33 UTC, GSemikozov commented on components/cards/cards.css
> +.container {
нужно создать отдельный блок container как мы это обсуждали

2023-03-18 21:33 UTC, GSemikozov commented on components/cards/cards.css
> +.cards {
если блок .cards - значит внутри описываем только его классы - класс блока, а также его элементов и модификаторов. => ниже запись `.card__item` означает что указываем стили для элемента блока .card (не .cards), так что card надо вынести в отдельный файл и оформить как отдельный блок

2023-03-26 19:47 UTC, GSemikozov requested changes

2023-03-26 19:47 UTC, GSemikozov commented on components/container/container.css
> +    margin: 68px auto 204px auto;
должно быть `0 auto`

2023-03-27 11:27 UTC, GSemikozov approved these changes

2023-03-27 11:27 UTC, merged