Lecture 3 tooltip
js-tasks-ru/htmlcss-20230227_nadya-karandasheva pull request #12
Opened 2023-03-18 10:50 UTC by Nadya-Karandasheva

2023-03-18 10:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-18 21:34 UTC, GSemikozov requested changes

2023-03-18 21:34 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +                    <img src="../../assets/images/tooltip.svg">
svg через `img` ни в коем случае не вставляем, иначе теряется весь смысл векторной графики)

2023-03-20 09:55 UTC, GSemikozov approved these changes, later dismissed

2023-03-20 09:55 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-03-22 11:57 UTC, GSemikozov approved these changes

2023-03-22 11:57 UTC, merged