Lecture 3 calendar
js-tasks-ru/htmlcss-20230227_nadya-karandasheva pull request #13
Opened 2023-03-18 11:34 UTC by Nadya-Karandasheva

2023-03-18 11:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-18 21:35 UTC, GSemikozov requested changes

2023-03-18 21:35 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 36px;
`28px 26px 32px`

2023-03-18 21:35 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_day {
еще не хватает модификаторов для выделения дат "от-до"

2023-03-19 07:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-19 07:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-20 09:55 UTC, GSemikozov approved these changes, later dismissed

2023-03-20 09:55 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-03-20 17:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-20 17:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-20 20:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-20 20:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-22 11:58 UTC, GSemikozov approved these changes

2023-03-22 11:58 UTC, merged