lecture 5 input
js-tasks-ru/htmlcss-20230227_nadya-karandasheva pull request #20
Opened 2023-03-27 14:01 UTC by Nadya-Karandasheva

2023-03-27 14:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-29 08:52 UTC, GSemikozov requested changes

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label class="input">
а вот в случае с сгруппированным компонентов формы все заворачивать в лейбл не надо)

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    width: 350px;
лишнее ограничение

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    position: absolute;
плейсхолер пишется на месте value / текста который вводит пользователь, он не позиционируется абсолютом, это лишнее, здесь достаточно задать только цвет)

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field::-webkit-input-placeholder {
.input__field::placeholder

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    border: 1px solid #4263EB;
можно просто border-color

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    border-radius: 8px;
радиусы при фокусе не меняются

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field.input_invalid:focus {
.input_invalid .input__field {}

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.icon_success {
success и error позиционируются одинаково, это означает что это один элемент .icon, а модификаторы - нужны лишь чтобы показывать правильную иконку при определенном состоянии блока

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.icon_hidden {
просто .icon, которая по умолчанию display: none;

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_invalid {
это модификатор блока, не элемента input, поэтому тут и так нет outline, а border + shadow - задается на уровне .input__field

2023-03-29 08:52 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_invalid {
и не вижу аналогичного для success (а именно от него и зависит, показывать ли соответствующую иконку)

2023-03-30 10:38 UTC, GSemikozov requested changes

2023-03-30 10:38 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <div class="input">
input__wrapper

2023-03-30 10:38 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <label for="input" ></label>
input__label

2023-03-30 10:38 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> -
все элементы блока должны быть завернуты в div с классом блока (input)

2023-03-30 10:38 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <svg class="icon icon_success" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
input__icon input__icon_success

2023-03-30 10:38 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <svg class="icon icon_invalid" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
и тут

2023-03-30 10:38 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.icon {
input__icon

2023-03-30 10:38 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    border: 1px solid var(--red);
меняем только border-color

2023-03-30 10:38 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field:focus ~ .icon {
по умолчанию просто .input__icon display: none

2023-03-31 16:41 UTC, GSemikozov requested changes

2023-03-31 16:41 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label for="input__label" >
в лейбл заворачивать не надо, это самостоятельный элемент, связать с инпутом - через `for + id`)

2023-03-31 16:56 UTC, GSemikozov approved these changes

2023-03-31 16:56 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-03-31 16:57 UTC, GSemikozov approved these changes

2023-03-31 16:57 UTC, merged