Lecture 3 modal
js-tasks-ru/htmlcss-20230227_nadya-karandasheva pull request #21
Opened 2023-03-29 11:33 UTC by Nadya-Karandasheva

2023-03-29 11:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-29 12:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-30 10:35 UTC, GSemikozov requested changes

2023-03-30 10:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal{
.modal

2023-03-30 10:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background: #C4C4C4;
фон задаем через rgba

2023-03-30 10:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
fixed

2023-03-30 10:35 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-close {
.modal__close

2023-03-31 13:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-31 13:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-31 16:41 UTC, GSemikozov requested changes

2023-03-31 16:41 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal-close {
.modal__close

2023-03-31 16:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-31 16:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-31 16:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-31 16:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-31 16:56 UTC, GSemikozov approved these changes

2023-03-31 16:56 UTC, merged